--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    mpin character varying(128)
);


ALTER TABLE public.accounts_user OWNER TO postgres;

--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_user_groups OWNER TO postgres;

--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_user_user_permissions OWNER TO postgres;

--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: portfolio_stock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.portfolio_stock (
    id bigint NOT NULL,
    company character varying(255) NOT NULL,
    symbol character varying(50) NOT NULL,
    portfolio character varying(20) NOT NULL,
    sector character varying(100) NOT NULL,
    ltp double precision,
    change_percent double precision,
    market_cap character varying(100),
    high_52w double precision,
    low_52w double precision,
    volume character varying(100)
);


ALTER TABLE public.portfolio_stock OWNER TO postgres;

--
-- Name: portfolio_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.portfolio_stock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portfolio_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, mpin) FROM stdin;
1	pbkdf2_sha256$1000000$Ae5Fkb3L6jYcWnQ8yMV7o9$kN0RFscz6l/D67xACzPBKQ+bji5zg9bKpvmUW+6jYGM=	\N	f	bhairavi				f	t	2026-03-25 00:00:08.966973+05:30	pbkdf2_sha256$1000000$VWuShBY1nPqueENsCXj0zb$9VptYPD/J2O+ckl9WlTV5m2ZGXbBTTtPtm3Wpz4Ep3Q=
\.


--
-- Data for Name: accounts_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add user	1	add_user
2	Can change user	1	change_user
3	Can delete user	1	delete_user
4	Can view user	1	view_user
5	Can add log entry	2	add_logentry
6	Can change log entry	2	change_logentry
7	Can delete log entry	2	delete_logentry
8	Can view log entry	2	view_logentry
9	Can add permission	3	add_permission
10	Can change permission	3	change_permission
11	Can delete permission	3	delete_permission
12	Can view permission	3	view_permission
13	Can add group	4	add_group
14	Can change group	4	change_group
15	Can delete group	4	delete_group
16	Can view group	4	view_group
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add stock	7	add_stock
26	Can change stock	7	change_stock
27	Can delete stock	7	delete_stock
28	Can view stock	7	view_stock
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	accounts	user
2	admin	logentry
3	auth	permission
4	auth	group
5	contenttypes	contenttype
6	sessions	session
7	portfolio	stock
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-03-24 23:22:06.799579+05:30
2	contenttypes	0002_remove_content_type_name	2026-03-24 23:22:06.812259+05:30
3	auth	0001_initial	2026-03-24 23:22:06.866835+05:30
4	auth	0002_alter_permission_name_max_length	2026-03-24 23:22:06.875383+05:30
5	auth	0003_alter_user_email_max_length	2026-03-24 23:22:06.885491+05:30
6	auth	0004_alter_user_username_opts	2026-03-24 23:22:06.895482+05:30
7	auth	0005_alter_user_last_login_null	2026-03-24 23:22:06.900277+05:30
8	auth	0006_require_contenttypes_0002	2026-03-24 23:22:06.902284+05:30
9	auth	0007_alter_validators_add_error_messages	2026-03-24 23:22:06.910559+05:30
10	auth	0008_alter_user_username_max_length	2026-03-24 23:22:06.917097+05:30
11	auth	0009_alter_user_last_name_max_length	2026-03-24 23:22:06.924153+05:30
12	auth	0010_alter_group_name_max_length	2026-03-24 23:22:06.933088+05:30
13	auth	0011_update_proxy_permissions	2026-03-24 23:22:06.939402+05:30
14	auth	0012_alter_user_first_name_max_length	2026-03-24 23:22:06.946274+05:30
15	accounts	0001_initial	2026-03-24 23:22:07.004247+05:30
16	admin	0001_initial	2026-03-24 23:22:07.029132+05:30
17	admin	0002_logentry_remove_auto_add	2026-03-24 23:22:07.037688+05:30
18	admin	0003_logentry_add_action_flag_choices	2026-03-24 23:22:07.046501+05:30
19	sessions	0001_initial	2026-03-24 23:22:07.062324+05:30
20	portfolio	0001_initial	2026-03-24 23:25:31.160729+05:30
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: portfolio_stock; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.portfolio_stock (id, company, symbol, portfolio, sector, ltp, change_percent, market_cap, high_52w, low_52w, volume) FROM stdin;
601	360 ONE WAM Ltd.	360ONE	NIFTY200	Financial Services	\N	\N		\N	\N	
602	ABB India Ltd.	ABB	NIFTY200	Capital Goods	\N	\N		\N	\N	
603	ACC Ltd.	ACC	NIFTY200	Construction Materials	\N	\N		\N	\N	
604	APL Apollo Tubes Ltd.	APLAPOLLO	NIFTY200	Capital Goods	\N	\N		\N	\N	
605	AU Small Finance Bank Ltd.	AUBANK	NIFTY200	Financial Services	\N	\N		\N	\N	
606	Adani Energy Solutions Ltd.	ADANIENSOL	NIFTY200	Power	\N	\N		\N	\N	
607	Adani Enterprises Ltd.	ADANIENT	NIFTY200	Metals & Mining	\N	\N		\N	\N	
608	Adani Green Energy Ltd.	ADANIGREEN	NIFTY200	Power	\N	\N		\N	\N	
609	Adani Ports and Special Economic Zone Ltd.	ADANIPORTS	NIFTY200	Services	\N	\N		\N	\N	
610	Adani Power Ltd.	ADANIPOWER	NIFTY200	Power	\N	\N		\N	\N	
611	Adani Total Gas Ltd.	ATGL	NIFTY200	Oil Gas & Consumable Fuels	\N	\N		\N	\N	
612	Aditya Birla Capital Ltd.	ABCAPITAL	NIFTY200	Financial Services	\N	\N		\N	\N	
613	Alkem Laboratories Ltd.	ALKEM	NIFTY200	Healthcare	\N	\N		\N	\N	
614	Ambuja Cements Ltd.	AMBUJACEM	NIFTY200	Construction Materials	\N	\N		\N	\N	
615	Apollo Hospitals Enterprise Ltd.	APOLLOHOSP	NIFTY200	Healthcare	\N	\N		\N	\N	
616	Ashok Leyland Ltd.	ASHOKLEY	NIFTY200	Capital Goods	\N	\N		\N	\N	
617	Asian Paints Ltd.	ASIANPAINT	NIFTY200	Consumer Durables	\N	\N		\N	\N	
618	Astral Ltd.	ASTRAL	NIFTY200	Capital Goods	\N	\N		\N	\N	
619	Aurobindo Pharma Ltd.	AUROPHARMA	NIFTY200	Healthcare	\N	\N		\N	\N	
620	Avenue Supermarts Ltd.	DMART	NIFTY200	Consumer Services	\N	\N		\N	\N	
621	Axis Bank Ltd.	AXISBANK	NIFTY200	Financial Services	\N	\N		\N	\N	
622	BSE Ltd.	BSE	NIFTY200	Financial Services	\N	\N		\N	\N	
623	Bajaj Auto Ltd.	BAJAJ-AUTO	NIFTY200	Automobile and Auto Components	\N	\N		\N	\N	
624	Bajaj Finance Ltd.	BAJFINANCE	NIFTY200	Financial Services	\N	\N		\N	\N	
625	Bajaj Finserv Ltd.	BAJAJFINSV	NIFTY200	Financial Services	\N	\N		\N	\N	
626	Bajaj Holdings & Investment Ltd.	BAJAJHLDNG	NIFTY200	Financial Services	\N	\N		\N	\N	
627	Bajaj Housing Finance Ltd.	BAJAJHFL	NIFTY200	Financial Services	\N	\N		\N	\N	
628	Bank of Baroda	BANKBARODA	NIFTY200	Financial Services	\N	\N		\N	\N	
629	Bank of India	BANKINDIA	NIFTY200	Financial Services	\N	\N		\N	\N	
630	Bharat Dynamics Ltd.	BDL	NIFTY200	Capital Goods	\N	\N		\N	\N	
631	Bharat Electronics Ltd.	BEL	NIFTY200	Capital Goods	\N	\N		\N	\N	
632	Bharat Forge Ltd.	BHARATFORG	NIFTY200	Automobile and Auto Components	\N	\N		\N	\N	
633	Bharat Heavy Electricals Ltd.	BHEL	NIFTY200	Capital Goods	\N	\N		\N	\N	
634	Bharat Petroleum Corporation Ltd.	BPCL	NIFTY200	Oil Gas & Consumable Fuels	\N	\N		\N	\N	
635	Bharti Airtel Ltd.	BHARTIARTL	NIFTY200	Telecommunication	\N	\N		\N	\N	
636	Bharti Hexacom Ltd.	BHARTIHEXA	NIFTY200	Telecommunication	\N	\N		\N	\N	
637	Biocon Ltd.	BIOCON	NIFTY200	Healthcare	\N	\N		\N	\N	
638	Blue Star Ltd.	BLUESTARCO	NIFTY200	Consumer Durables	\N	\N		\N	\N	
639	Bosch Ltd.	BOSCHLTD	NIFTY200	Automobile and Auto Components	\N	\N		\N	\N	
640	Britannia Industries Ltd.	BRITANNIA	NIFTY200	Fast Moving Consumer Goods	\N	\N		\N	\N	
641	CG Power and Industrial Solutions Ltd.	CGPOWER	NIFTY200	Capital Goods	\N	\N		\N	\N	
642	Canara Bank	CANBK	NIFTY200	Financial Services	\N	\N		\N	\N	
643	Cholamandalam Investment and Finance Company Ltd.	CHOLAFIN	NIFTY200	Financial Services	\N	\N		\N	\N	
644	Cipla Ltd.	CIPLA	NIFTY200	Healthcare	\N	\N		\N	\N	
645	Coal India Ltd.	COALINDIA	NIFTY200	Oil Gas & Consumable Fuels	\N	\N		\N	\N	
646	Cochin Shipyard Ltd.	COCHINSHIP	NIFTY200	Capital Goods	\N	\N		\N	\N	
647	Coforge Ltd.	COFORGE	NIFTY200	Information Technology	\N	\N		\N	\N	
648	Colgate Palmolive (India) Ltd.	COLPAL	NIFTY200	Fast Moving Consumer Goods	\N	\N		\N	\N	
649	Container Corporation of India Ltd.	CONCOR	NIFTY200	Services	\N	\N		\N	\N	
650	Coromandel International Ltd.	COROMANDEL	NIFTY200	Chemicals	\N	\N		\N	\N	
651	Cummins India Ltd.	CUMMINSIND	NIFTY200	Capital Goods	\N	\N		\N	\N	
652	DLF Ltd.	DLF	NIFTY200	Realty	\N	\N		\N	\N	
653	Dabur India Ltd.	DABUR	NIFTY200	Fast Moving Consumer Goods	\N	\N		\N	\N	
654	Divi's Laboratories Ltd.	DIVISLAB	NIFTY200	Healthcare	\N	\N		\N	\N	
655	Dixon Technologies (India) Ltd.	DIXON	NIFTY200	Consumer Durables	\N	\N		\N	\N	
656	Dr. Reddy's Laboratories Ltd.	DRREDDY	NIFTY200	Healthcare	\N	\N		\N	\N	
657	Eicher Motors Ltd.	EICHERMOT	NIFTY200	Automobile and Auto Components	\N	\N		\N	\N	
658	Eternal Ltd.	ETERNAL	NIFTY200	Consumer Services	\N	\N		\N	\N	
659	Exide Industries Ltd.	EXIDEIND	NIFTY200	Automobile and Auto Components	\N	\N		\N	\N	
660	FSN E-Commerce Ventures Ltd.	NYKAA	NIFTY200	Consumer Services	\N	\N		\N	\N	
661	Federal Bank Ltd.	FEDERALBNK	NIFTY200	Financial Services	\N	\N		\N	\N	
662	Fortis Healthcare Ltd.	FORTIS	NIFTY200	Healthcare	\N	\N		\N	\N	
663	GAIL (India) Ltd.	GAIL	NIFTY200	Oil Gas & Consumable Fuels	\N	\N		\N	\N	
664	GMR Airports Ltd.	GMRAIRPORT	NIFTY200	Services	\N	\N		\N	\N	
665	Glenmark Pharmaceuticals Ltd.	GLENMARK	NIFTY200	Healthcare	\N	\N		\N	\N	
666	Godfrey Phillips India Ltd.	GODFRYPHLP	NIFTY200	Fast Moving Consumer Goods	\N	\N		\N	\N	
667	Godrej Consumer Products Ltd.	GODREJCP	NIFTY200	Fast Moving Consumer Goods	\N	\N		\N	\N	
668	Godrej Properties Ltd.	GODREJPROP	NIFTY200	Realty	\N	\N		\N	\N	
669	Grasim Industries Ltd.	GRASIM	NIFTY200	Construction Materials	\N	\N		\N	\N	
670	HCL Technologies Ltd.	HCLTECH	NIFTY200	Information Technology	\N	\N		\N	\N	
671	HDFC Asset Management Company Ltd.	HDFCAMC	NIFTY200	Financial Services	\N	\N		\N	\N	
672	HDFC Bank Ltd.	HDFCBANK	NIFTY200	Financial Services	\N	\N		\N	\N	
673	HDFC Life Insurance Company Ltd.	HDFCLIFE	NIFTY200	Financial Services	\N	\N		\N	\N	
674	Havells India Ltd.	HAVELLS	NIFTY200	Consumer Durables	\N	\N		\N	\N	
675	Hero MotoCorp Ltd.	HEROMOTOCO	NIFTY200	Automobile and Auto Components	\N	\N		\N	\N	
676	Hindalco Industries Ltd.	HINDALCO	NIFTY200	Metals & Mining	\N	\N		\N	\N	
677	Hindustan Aeronautics Ltd.	HAL	NIFTY200	Capital Goods	\N	\N		\N	\N	
678	Hindustan Petroleum Corporation Ltd.	HINDPETRO	NIFTY200	Oil Gas & Consumable Fuels	\N	\N		\N	\N	
679	Hindustan Unilever Ltd.	HINDUNILVR	NIFTY200	Fast Moving Consumer Goods	\N	\N		\N	\N	
680	Hindustan Zinc Ltd.	HINDZINC	NIFTY200	Metals & Mining	\N	\N		\N	\N	
681	Hitachi Energy India Ltd.	POWERINDIA	NIFTY200	Capital Goods	\N	\N		\N	\N	
682	Housing & Urban Development Corporation Ltd.	HUDCO	NIFTY200	Financial Services	\N	\N		\N	\N	
683	Hyundai Motor India Ltd.	HYUNDAI	NIFTY200	Automobile and Auto Components	\N	\N		\N	\N	
684	ICICI Bank Ltd.	ICICIBANK	NIFTY200	Financial Services	\N	\N		\N	\N	
685	ICICI Lombard General Insurance Company Ltd.	ICICIGI	NIFTY200	Financial Services	\N	\N		\N	\N	
686	IDFC First Bank Ltd.	IDFCFIRSTB	NIFTY200	Financial Services	\N	\N		\N	\N	
687	IRB Infrastructure Developers Ltd.	IRB	NIFTY200	Construction	\N	\N		\N	\N	
688	ITC Hotels Ltd.	ITCHOTELS	NIFTY200	Consumer Services	\N	\N		\N	\N	
689	ITC Ltd.	ITC	NIFTY200	Fast Moving Consumer Goods	\N	\N		\N	\N	
690	Indian Bank	INDIANB	NIFTY200	Financial Services	\N	\N		\N	\N	
691	Indian Hotels Co. Ltd.	INDHOTEL	NIFTY200	Consumer Services	\N	\N		\N	\N	
692	Indian Oil Corporation Ltd.	IOC	NIFTY200	Oil Gas & Consumable Fuels	\N	\N		\N	\N	
693	Indian Railway Catering And Tourism Corporation Ltd.	IRCTC	NIFTY200	Consumer Services	\N	\N		\N	\N	
694	Indian Railway Finance Corporation Ltd.	IRFC	NIFTY200	Financial Services	\N	\N		\N	\N	
695	Indian Renewable Energy Development Agency Ltd.	IREDA	NIFTY200	Financial Services	\N	\N		\N	\N	
696	Indraprastha Gas Ltd.	IGL	NIFTY200	Oil Gas & Consumable Fuels	\N	\N		\N	\N	
697	Indus Towers Ltd.	INDUSTOWER	NIFTY200	Telecommunication	\N	\N		\N	\N	
698	IndusInd Bank Ltd.	INDUSINDBK	NIFTY200	Financial Services	\N	\N		\N	\N	
699	Info Edge (India) Ltd.	NAUKRI	NIFTY200	Consumer Services	\N	\N		\N	\N	
700	Infosys Ltd.	INFY	NIFTY200	Information Technology	\N	\N		\N	\N	
701	InterGlobe Aviation Ltd.	INDIGO	NIFTY200	Services	\N	\N		\N	\N	
702	JSW Energy Ltd.	JSWENERGY	NIFTY200	Power	\N	\N		\N	\N	
703	JSW Steel Ltd.	JSWSTEEL	NIFTY200	Metals & Mining	\N	\N		\N	\N	
704	Jindal Steel Ltd.	JINDALSTEL	NIFTY200	Metals & Mining	\N	\N		\N	\N	
705	Jio Financial Services Ltd.	JIOFIN	NIFTY200	Financial Services	\N	\N		\N	\N	
706	Jubilant Foodworks Ltd.	JUBLFOOD	NIFTY200	Consumer Services	\N	\N		\N	\N	
707	KEI Industries Ltd.	KEI	NIFTY200	Capital Goods	\N	\N		\N	\N	
708	KPIT Technologies Ltd.	KPITTECH	NIFTY200	Information Technology	\N	\N		\N	\N	
709	Kalyan Jewellers India Ltd.	KALYANKJIL	NIFTY200	Consumer Durables	\N	\N		\N	\N	
710	Kotak Mahindra Bank Ltd.	KOTAKBANK	NIFTY200	Financial Services	\N	\N		\N	\N	
711	L&T Finance Ltd.	LTF	NIFTY200	Financial Services	\N	\N		\N	\N	
712	LIC Housing Finance Ltd.	LICHSGFIN	NIFTY200	Financial Services	\N	\N		\N	\N	
713	LTIMindtree Ltd.	LTM	NIFTY200	Information Technology	\N	\N		\N	\N	
714	Larsen & Toubro Ltd.	LT	NIFTY200	Construction	\N	\N		\N	\N	
715	Life Insurance Corporation of India	LICI	NIFTY200	Financial Services	\N	\N		\N	\N	
716	Lodha Developers Ltd.	LODHA	NIFTY200	Realty	\N	\N		\N	\N	
717	Lupin Ltd.	LUPIN	NIFTY200	Healthcare	\N	\N		\N	\N	
718	MRF Ltd.	MRF	NIFTY200	Automobile and Auto Components	\N	\N		\N	\N	
719	Mahindra & Mahindra Financial Services Ltd.	M&MFIN	NIFTY200	Financial Services	\N	\N		\N	\N	
720	Mahindra & Mahindra Ltd.	M&M	NIFTY200	Automobile and Auto Components	\N	\N		\N	\N	
721	Mankind Pharma Ltd.	MANKIND	NIFTY200	Healthcare	\N	\N		\N	\N	
722	Marico Ltd.	MARICO	NIFTY200	Fast Moving Consumer Goods	\N	\N		\N	\N	
723	Maruti Suzuki India Ltd.	MARUTI	NIFTY200	Automobile and Auto Components	\N	\N		\N	\N	
724	Max Financial Services Ltd.	MFSL	NIFTY200	Financial Services	\N	\N		\N	\N	
725	Max Healthcare Institute Ltd.	MAXHEALTH	NIFTY200	Healthcare	\N	\N		\N	\N	
726	Mazagoan Dock Shipbuilders Ltd.	MAZDOCK	NIFTY200	Capital Goods	\N	\N		\N	\N	
727	Motilal Oswal Financial Services Ltd.	MOTILALOFS	NIFTY200	Financial Services	\N	\N		\N	\N	
728	MphasiS Ltd.	MPHASIS	NIFTY200	Information Technology	\N	\N		\N	\N	
729	Muthoot Finance Ltd.	MUTHOOTFIN	NIFTY200	Financial Services	\N	\N		\N	\N	
730	NHPC Ltd.	NHPC	NIFTY200	Power	\N	\N		\N	\N	
731	NMDC Ltd.	NMDC	NIFTY200	Metals & Mining	\N	\N		\N	\N	
732	NTPC Green Energy Ltd.	NTPCGREEN	NIFTY200	Power	\N	\N		\N	\N	
733	NTPC Ltd.	NTPC	NIFTY200	Power	\N	\N		\N	\N	
734	National Aluminium Co. Ltd.	NATIONALUM	NIFTY200	Metals & Mining	\N	\N		\N	\N	
735	Nestle India Ltd.	NESTLEIND	NIFTY200	Fast Moving Consumer Goods	\N	\N		\N	\N	
736	Oberoi Realty Ltd.	OBEROIRLTY	NIFTY200	Realty	\N	\N		\N	\N	
737	Oil & Natural Gas Corporation Ltd.	ONGC	NIFTY200	Oil Gas & Consumable Fuels	\N	\N		\N	\N	
738	Oil India Ltd.	OIL	NIFTY200	Oil Gas & Consumable Fuels	\N	\N		\N	\N	
739	One 97 Communications Ltd.	PAYTM	NIFTY200	Financial Services	\N	\N		\N	\N	
740	Oracle Financial Services Software Ltd.	OFSS	NIFTY200	Information Technology	\N	\N		\N	\N	
741	PB Fintech Ltd.	POLICYBZR	NIFTY200	Financial Services	\N	\N		\N	\N	
742	PI Industries Ltd.	PIIND	NIFTY200	Chemicals	\N	\N		\N	\N	
743	Page Industries Ltd.	PAGEIND	NIFTY200	Textiles	\N	\N		\N	\N	
744	Patanjali Foods Ltd.	PATANJALI	NIFTY200	Fast Moving Consumer Goods	\N	\N		\N	\N	
745	Persistent Systems Ltd.	PERSISTENT	NIFTY200	Information Technology	\N	\N		\N	\N	
746	Phoenix Mills Ltd.	PHOENIXLTD	NIFTY200	Realty	\N	\N		\N	\N	
747	Pidilite Industries Ltd.	PIDILITIND	NIFTY200	Chemicals	\N	\N		\N	\N	
748	Polycab India Ltd.	POLYCAB	NIFTY200	Capital Goods	\N	\N		\N	\N	
749	Power Finance Corporation Ltd.	PFC	NIFTY200	Financial Services	\N	\N		\N	\N	
750	Power Grid Corporation of India Ltd.	POWERGRID	NIFTY200	Power	\N	\N		\N	\N	
751	Premier Energies Ltd.	PREMIERENE	NIFTY200	Capital Goods	\N	\N		\N	\N	
752	Prestige Estates Projects Ltd.	PRESTIGE	NIFTY200	Realty	\N	\N		\N	\N	
753	Punjab National Bank	PNB	NIFTY200	Financial Services	\N	\N		\N	\N	
754	REC Ltd.	RECLTD	NIFTY200	Financial Services	\N	\N		\N	\N	
755	Rail Vikas Nigam Ltd.	RVNL	NIFTY200	Construction	\N	\N		\N	\N	
756	Reliance Industries Ltd.	RELIANCE	NIFTY200	Oil Gas & Consumable Fuels	\N	\N		\N	\N	
757	SBI Cards and Payment Services Ltd.	SBICARD	NIFTY200	Financial Services	\N	\N		\N	\N	
758	SBI Life Insurance Company Ltd.	SBILIFE	NIFTY200	Financial Services	\N	\N		\N	\N	
759	SRF Ltd.	SRF	NIFTY200	Chemicals	\N	\N		\N	\N	
760	Samvardhana Motherson International Ltd.	MOTHERSON	NIFTY200	Automobile and Auto Components	\N	\N		\N	\N	
761	Shree Cement Ltd.	SHREECEM	NIFTY200	Construction Materials	\N	\N		\N	\N	
762	Shriram Finance Ltd.	SHRIRAMFIN	NIFTY200	Financial Services	\N	\N		\N	\N	
763	Siemens Energy India Ltd.	ENRIN	NIFTY200	Capital Goods	\N	\N		\N	\N	
764	Siemens Ltd.	SIEMENS	NIFTY200	Capital Goods	\N	\N		\N	\N	
765	Solar Industries India Ltd.	SOLARINDS	NIFTY200	Chemicals	\N	\N		\N	\N	
766	Sona BLW Precision Forgings Ltd.	SONACOMS	NIFTY200	Automobile and Auto Components	\N	\N		\N	\N	
767	State Bank of India	SBIN	NIFTY200	Financial Services	\N	\N		\N	\N	
768	Steel Authority of India Ltd.	SAIL	NIFTY200	Metals & Mining	\N	\N		\N	\N	
769	Sun Pharmaceutical Industries Ltd.	SUNPHARMA	NIFTY200	Healthcare	\N	\N		\N	\N	
770	Supreme Industries Ltd.	SUPREMEIND	NIFTY200	Capital Goods	\N	\N		\N	\N	
771	Suzlon Energy Ltd.	SUZLON	NIFTY200	Capital Goods	\N	\N		\N	\N	
772	Swiggy Ltd.	SWIGGY	NIFTY200	Consumer Services	\N	\N		\N	\N	
773	TVS Motor Company Ltd.	TVSMOTOR	NIFTY200	Automobile and Auto Components	\N	\N		\N	\N	
774	Tata Communications Ltd.	TATACOMM	NIFTY200	Telecommunication	\N	\N		\N	\N	
775	Tata Consultancy Services Ltd.	TCS	NIFTY200	Information Technology	\N	\N		\N	\N	
776	Tata Consumer Products Ltd.	TATACONSUM	NIFTY200	Fast Moving Consumer Goods	\N	\N		\N	\N	
777	Tata Elxsi Ltd.	TATAELXSI	NIFTY200	Information Technology	\N	\N		\N	\N	
778	Tata Motors Passenger Vehicles Ltd.	TMPV	NIFTY200	Automobile and Auto Components	\N	\N		\N	\N	
779	Tata Power Co. Ltd.	TATAPOWER	NIFTY200	Power	\N	\N		\N	\N	
780	Tata Steel Ltd.	TATASTEEL	NIFTY200	Metals & Mining	\N	\N		\N	\N	
781	Tata Technologies Ltd.	TATATECH	NIFTY200	Information Technology	\N	\N		\N	\N	
782	Tech Mahindra Ltd.	TECHM	NIFTY200	Information Technology	\N	\N		\N	\N	
783	Titan Company Ltd.	TITAN	NIFTY200	Consumer Durables	\N	\N		\N	\N	
784	Torrent Pharmaceuticals Ltd.	TORNTPHARM	NIFTY200	Healthcare	\N	\N		\N	\N	
785	Torrent Power Ltd.	TORNTPOWER	NIFTY200	Power	\N	\N		\N	\N	
786	Trent Ltd.	TRENT	NIFTY200	Consumer Services	\N	\N		\N	\N	
787	Tube Investments of India Ltd.	TIINDIA	NIFTY200	Automobile and Auto Components	\N	\N		\N	\N	
788	UPL Ltd.	UPL	NIFTY200	Chemicals	\N	\N		\N	\N	
789	UltraTech Cement Ltd.	ULTRACEMCO	NIFTY200	Construction Materials	\N	\N		\N	\N	
790	Union Bank of India	UNIONBANK	NIFTY200	Financial Services	\N	\N		\N	\N	
791	United Spirits Ltd.	UNITDSPR	NIFTY200	Fast Moving Consumer Goods	\N	\N		\N	\N	
792	Varun Beverages Ltd.	VBL	NIFTY200	Fast Moving Consumer Goods	\N	\N		\N	\N	
793	Vedanta Ltd.	VEDL	NIFTY200	Metals & Mining	\N	\N		\N	\N	
794	Vishal Mega Mart Ltd.	VMM	NIFTY200	Consumer Services	\N	\N		\N	\N	
795	Vodafone Idea Ltd.	IDEA	NIFTY200	Telecommunication	\N	\N		\N	\N	
796	Voltas Ltd.	VOLTAS	NIFTY200	Consumer Durables	\N	\N		\N	\N	
797	Waaree Energies Ltd.	WAAREEENER	NIFTY200	Capital Goods	\N	\N		\N	\N	
798	Wipro Ltd.	WIPRO	NIFTY200	Information Technology	\N	\N		\N	\N	
799	Yes Bank Ltd.	YESBANK	NIFTY200	Financial Services	\N	\N		\N	\N	
800	Zydus Lifesciences Ltd.	ZYDUSLIFE	NIFTY200	Healthcare	\N	\N		\N	\N	
801	Nvidia	NVDA	USA200	Technology	172.7	\N		\N	\N	
802	Apple Inc.	AAPL	USA200	Technology	247.99	\N		\N	\N	
803	Microsoft	MSFT	USA200	Technology	381.87	\N		\N	\N	
804	Amazon	AMZN	USA200	Consumer Discretionary	205.37	\N		\N	\N	
805	Alphabet Inc. (Class A)	GOOGL	USA200	Communication Services	301	\N		\N	\N	
806	Alphabet Inc. (Class C)	GOOG	USA200	Communication Services	298.79	\N		\N	\N	
807	Meta Platforms	META	USA200	Communication Services	593.66	\N		\N	\N	
808	Broadcom	AVGO	USA200	Technology	310.51	\N		\N	\N	
809	Tesla Inc.	TSLA	USA200	Consumer Discretionary	367.96	\N		\N	\N	
810	Berkshire Hathaway	BRK.B	USA200	Financials	480.94	\N		\N	\N	
811	Walmart	WMT	USA200	Consumer Staples	119.02	\N		\N	\N	
812	Lilly (Eli)	LLY	USA200	Healthcare	906.7	\N		\N	\N	
813	JPMorgan Chase	JPM	USA200	Financials	286.56	\N		\N	\N	
814	ExxonMobil	XOM	USA200	Energy	159.67	\N		\N	\N	
815	Visa Inc.	V	USA200	Financials	301.62	\N		\N	\N	
816	Johnson & Johnson	JNJ	USA200	Healthcare	235.37	\N		\N	\N	
817	Micron Technology	MU	USA200	Technology	422.9	\N		\N	\N	
818	Mastercard	MA	USA200	Financials	496.32	\N		\N	\N	
819	Costco	COST	USA200	Consumer Staples	972.33	\N		\N	\N	
820	Oracle Corporation	ORCL	USA200	Technology	149.68	\N		\N	\N	
821	Chevron Corporation	CVX	USA200	Energy	201.73	\N		\N	\N	
822	Netflix	NFLX	USA200	Communication Services	91.82	\N		\N	\N	
823	AbbVie	ABBV	USA200	Healthcare	205.07	\N		\N	\N	
824	Palantir Technologies	PLTR	USA200	Technology	150.68	\N		\N	\N	
825	Bank of America	BAC	USA200	Financials	47.16	\N		\N	\N	
826	Procter & Gamble	PG	USA200	Consumer Staples	144.28	\N		\N	\N	
827	Advanced Micro Devices	AMD	USA200	Technology	201.33	\N		\N	\N	
828	Coca-Cola Company (The)	KO	USA200	Consumer Staples	74.75	\N		\N	\N	
829	Home Depot (The)	HD	USA200	Consumer Discretionary	320.75	\N		\N	\N	
830	Caterpillar Inc.	CAT	USA200	Industrials	680.88	\N		\N	\N	
831	Cisco	CSCO	USA200	Technology	77.65	\N		\N	\N	
832	GE Aerospace	GE	USA200	Industrials	286.79	\N		\N	\N	
833	Lam Research	LRCX	USA200	Technology	228.36	\N		\N	\N	
834	Applied Materials	AMAT	USA200	Technology	357.06	\N		\N	\N	
835	Merck & Co.	MRK	USA200	Healthcare	114.18	\N		\N	\N	
836	RTX Corporation	RTX	USA200	Industrials	198.16	\N		\N	\N	
837	Morgan Stanley	MS	USA200	Financials	161.47	\N		\N	\N	
838	Philip Morris International	PM	USA200	Consumer Staples	163.11	\N		\N	\N	
839	UnitedHealth Group	UNH	USA200	Healthcare	275.59	\N		\N	\N	
840	Goldman Sachs	GS	USA200	Financials	813.53	\N		\N	\N	
841	Wells Fargo	WFC	USA200	Financials	77.6	\N		\N	\N	
842	T-Mobile US	TMUS	USA200	Communication Services	208.47	\N		\N	\N	
843	GE Vernova	GEV	USA200	Industrials	851.07	\N		\N	\N	
844	IBM	IBM	USA200	Technology	241.77	\N		\N	\N	
845	Linde plc	LIN	USA200	Materials	488.15	\N		\N	\N	
846	McDonald's	MCD	USA200	Consumer Discretionary	308.85	\N		\N	\N	
847	Intel	INTC	USA200	Technology	43.87	\N		\N	\N	
848	Verizon	VZ	USA200	Communication Services	49.98	\N		\N	\N	
849	PepsiCo	PEP	USA200	Consumer Staples	150.04	\N		\N	\N	
850	American Express	AXP	USA200	Financials	295.5	\N		\N	\N	
851	AT&T	T	USA200	Communication Services	28.31	\N		\N	\N	
852	KLA Corporation	KLAC	USA200	Technology	1498.67	\N		\N	\N	
853	Citigroup	C	USA200	Financials	109.52	\N		\N	\N	
854	Amgen	AMGN	USA200	Healthcare	347.8	\N		\N	\N	
855	NextEra Energy	NEE	USA200	Utilities	89.5	\N		\N	\N	
856	Abbott Laboratories	ABT	USA200	Healthcare	105.46	\N		\N	\N	
857	Salesforce	CRM	USA200	Technology	195.38	\N		\N	\N	
858	Walt Disney Company (The)	DIS	USA200	Communication Services	99.51	\N		\N	\N	
859	Thermo Fisher Scientific	TMO	USA200	Healthcare	474.39	\N		\N	\N	
860	TJX Companies	TJX	USA200	Consumer Discretionary	154.98	\N		\N	\N	
861	Texas Instruments	TXN	USA200	Technology	187.19	\N		\N	\N	
862	Gilead Sciences	GILD	USA200	Healthcare	137.21	\N		\N	\N	
863	Intuitive Surgical	ISRG	USA200	Healthcare	477.97	\N		\N	\N	
864	Charles Schwab Corporation	SCHW	USA200	Financials	94.66	\N		\N	\N	
865	Arista Networks	ANET	USA200	Technology	131.22	\N		\N	\N	
866	Amphenol	APH	USA200	Technology	126.74	\N		\N	\N	
867	ConocoPhillips	COP	USA200	Energy	126.92	\N		\N	\N	
868	Pfizer	PFE	USA200	Healthcare	26.97	\N		\N	\N	
869	Boeing	BA	USA200	Industrials	195.12	\N		\N	\N	
870	Uber	UBER	USA200	Industrials	73.89	\N		\N	\N	
871	Deere & Company	DE	USA200	Industrials	559.73	\N		\N	\N	
872	Analog Devices	ADI	USA200	Technology	309.43	\N		\N	\N	
873	AppLovin Corporation	APP	USA200	Technology	442.39	\N		\N	\N	
874	BlackRock	BLK	USA200	Financials	957.91	\N		\N	\N	
875	Lockheed Martin	LMT	USA200	Industrials	627.43	\N		\N	\N	
876	Honeywell	HON	USA200	Industrials	221.5	\N		\N	\N	
877	Union Pacific Corporation	UNP	USA200	Industrials	234.92	\N		\N	\N	
878	Qualcomm	QCOM	USA200	Technology	129.9	\N		\N	\N	
879	Eaton Corporation	ETN	USA200	Industrials	356.8	\N		\N	\N	
880	Booking Holdings	BKNG	USA200	Consumer Discretionary	4324.04	\N		\N	\N	
881	Welltower	WELL	USA200	Real Estate	195.94	\N		\N	\N	
882	Danaher Corporation	DHR	USA200	Healthcare	189.35	\N		\N	\N	
883	Palo Alto Networks	PANW	USA200	Technology	162.95	\N		\N	\N	
884	Stryker Corporation	SYK	USA200	Healthcare	335.67	\N		\N	\N	
885	S&P Global	SPGI	USA200	Financials	424.43	\N		\N	\N	
886	Lowe's	LOW	USA200	Consumer Discretionary	224.63	\N		\N	\N	
887	Intuit	INTU	USA200	Technology	455.56	\N		\N	\N	
888	Chubb Limited	CB	USA200	Financials	322.58	\N		\N	\N	
889	Accenture	ACN	USA200	Technology	199.99	\N		\N	\N	
890	Progressive Corporation	PGR	USA200	Financials	206	\N		\N	\N	
891	Prologis	PLD	USA200	Real Estate	128.01	\N		\N	\N	
892	Bristol Myers Squibb	BMY	USA200	Healthcare	57.48	\N		\N	\N	
893	ServiceNow	NOW	USA200	Technology	110.38	\N		\N	\N	
894	Vertex Pharmaceuticals	VRTX	USA200	Healthcare	454	\N		\N	\N	
895	Parker Hannifin	PH	USA200	Industrials	894.41	\N		\N	\N	
896	Capital One	COF	USA200	Financials	181.46	\N		\N	\N	
897	Medtronic	MDT	USA200	Healthcare	86.16	\N		\N	\N	
898	HCA Healthcare	HCA	USA200	Healthcare	493.88	\N		\N	\N	
899	CME Group	CME	USA200	Financials	307.32	\N		\N	\N	
900	McKesson Corporation	MCK	USA200	Healthcare	885.84	\N		\N	\N	
901	Altria	MO	USA200	Consumer Staples	64.47	\N		\N	\N	
902	Corning Inc.	GLW	USA200	Technology	124.58	\N		\N	\N	
903	Starbucks	SBUX	USA200	Consumer Discretionary	92.55	\N		\N	\N	
904	Sandisk Corporation	SNDK	USA200	Technology	709.71	\N		\N	\N	
905	Southern Company	SO	USA200	Utilities	93.39	\N		\N	\N	
906	Comcast	CMCSA	USA200	Communication Services	29.02	\N		\N	\N	
907	Newmont	NEM	USA200	Materials	95.8	\N		\N	\N	
908	CrowdStrike	CRWD	USA200	Technology	409	\N		\N	\N	
909	Boston Scientific	BSX	USA200	Healthcare	69.48	\N		\N	\N	
910	Constellation Energy	CEG	USA200	Utilities	281.99	\N		\N	\N	
911	Dell Technologies	DELL	USA200	Technology	157.67	\N		\N	\N	
912	Adobe Inc.	ADBE	USA200	Technology	248.15	\N		\N	\N	
913	Northrop Grumman	NOC	USA200	Industrials	706.95	\N		\N	\N	
914	Western Digital	WDC	USA200	Technology	293.1	\N		\N	\N	
915	Duke Energy	DUK	USA200	Utilities	126.81	\N		\N	\N	
916	Equinix	EQIX	USA200	Real Estate	959.16	\N		\N	\N	
917	General Dynamics	GD	USA200	Industrials	345.78	\N		\N	\N	
918	Waste Management	WM	USA200	Industrials	231.24	\N		\N	\N	
919	Howmet Aerospace	HWM	USA200	Industrials	231.21	\N		\N	\N	
920	Seagate Technology	STX	USA200	Technology	411.23	\N		\N	\N	
921	CVS Health	CVS	USA200	Healthcare	71.48	\N		\N	\N	
922	Trane Technologies	TT	USA200	Industrials	410.36	\N		\N	\N	
923	Intercontinental Exchange	ICE	USA200	Financials	158.43	\N		\N	\N	
924	Williams Companies	WMB	USA200	Energy	72.41	\N		\N	\N	
925	Blackstone Inc.	BX	USA200	Financials	110.43	\N		\N	\N	
926	Marsh & McLennan Companies Inc.	MRSH	USA200	Financials	176.48	\N		\N	\N	
927	Marriott International	MAR	USA200	Consumer Discretionary	319.76	\N		\N	\N	
928	FedEx	FDX	USA200	Industrials	358.85	\N		\N	\N	
929	Automatic Data Processing	ADP	USA200	Industrials	208.69	\N		\N	\N	
930	Quanta Services	PWR	USA200	Industrials	555.39	\N		\N	\N	
931	American Tower	AMT	USA200	Real Estate	176.79	\N		\N	\N	
932	United Parcel Service	UPS	USA200	Industrials	95.86	\N		\N	\N	
933	PNC Financial Services	PNC	USA200	Financials	201.71	\N		\N	\N	
934	Synopsys	SNPS	USA200	Technology	420.32	\N		\N	\N	
935	KKR	KKR	USA200	Financials	90	\N		\N	\N	
936	U.S. Bancorp	USB	USA200	Financials	51.25	\N		\N	\N	
937	Johnson Controls	JCI	USA200	Industrials	129.7	\N		\N	\N	
938	BNY Mellon	BK	USA200	Financials	114.94	\N		\N	\N	
939	Cadence Design Systems	CDNS	USA200	Technology	283.9	\N		\N	\N	
940	Nike Inc.	NKE	USA200	Consumer Discretionary	52.37	\N		\N	\N	
941	Regeneron Pharmaceuticals	REGN	USA200	Healthcare	732.87	\N		\N	\N	
942	Moody's Corporation	MCO	USA200	Financials	435.12	\N		\N	\N	
943	Airbnb	ABNB	USA200	Consumer Discretionary	128.52	\N		\N	\N	
944	Sherwin-Williams	SHW	USA200	Materials	303.53	\N		\N	\N	
945	Motorola Solutions	MSI	USA200	Technology	452.35	\N		\N	\N	
946	Freeport-McMoRan	FCX	USA200	Materials	52.09	\N		\N	\N	
947	EOG Resources	EOG	USA200	Energy	138.73	\N		\N	\N	
948	3M	MMM	USA200	Industrials	141.2	\N		\N	\N	
949	Illinois Tool Works	ITW	USA200	Industrials	257.68	\N		\N	\N	
950	Cummins	CMI	USA200	Industrials	533.54	\N		\N	\N	
951	O'Reilly Auto Parts	ORLY	USA200	Consumer Discretionary	87.3	\N		\N	\N	
952	Kinder Morgan	KMI	USA200	Energy	32.84	\N		\N	\N	
953	Ecolab	ECL	USA200	Materials	256.48	\N		\N	\N	
954	Monster Beverage	MNST	USA200	Consumer Staples	73.69	\N		\N	\N	
955	Mondelez International	MDLZ	USA200	Consumer Staples	56.21	\N		\N	\N	
956	Emerson Electric	EMR	USA200	Industrials	128.15	\N		\N	\N	
957	Cintas	CTAS	USA200	Industrials	179.34	\N		\N	\N	
958	Valero Energy	VLO	USA200	Energy	239.86	\N		\N	\N	
959	Royal Caribbean Group	RCL	USA200	Consumer Discretionary	263.65	\N		\N	\N	
960	CSX Corporation	CSX	USA200	Industrials	38.17	\N		\N	\N	
961	Phillips 66	PSX	USA200	Energy	175.47	\N		\N	\N	
962	Schlumberger	SLB	USA200	Energy	46.63	\N		\N	\N	
963	Aon	AON	USA200	Financials	325.63	\N		\N	\N	
964	Cigna	CI	USA200	Healthcare	262.84	\N		\N	\N	
965	Marathon Petroleum	MPC	USA200	Energy	232.53	\N		\N	\N	
966	Ross Stores	ROST	USA200	Consumer Discretionary	211.19	\N		\N	\N	
967	Colgate-Palmolive	CL	USA200	Consumer Staples	85.12	\N		\N	\N	
968	DoorDash	DASH	USA200	Technology	156.64	\N		\N	\N	
969	Warner Bros. Discovery	WBD	USA200	Communication Services	27.42	\N		\N	\N	
970	American Electric Power	AEP	USA200	Utilities	125.66	\N		\N	\N	
971	Republic Services	RSG	USA200	Industrials	219.3	\N		\N	\N	
972	CRH plc	CRH	USA200	Materials	100.47	\N		\N	\N	
973	Hilton Worldwide	HLT	USA200	Consumer Discretionary	292.58	\N		\N	\N	
974	TransDigm Group	TDG	USA200	Industrials	1177.39	\N		\N	\N	
975	L3Harris	LHX	USA200	Industrials	352.85	\N		\N	\N	
976	General Motors	GM	USA200	Consumer Discretionary	72.81	\N		\N	\N	
977	Apollo Global Management	APO	USA200	Financials	112	\N		\N	\N	
978	Elevance Health	ELV	USA200	Healthcare	291.48	\N		\N	\N	
979	Travelers Companies (The)	TRV	USA200	Financials	296.6	\N		\N	\N	
980	Robinhood Markets Inc.	HOOD	USA200	Financials	70.89	\N		\N	\N	
981	Cencora	COR	USA200	Healthcare	326.91	\N		\N	\N	
982	Norfolk Southern Railway	NSC	USA200	Industrials	281.09	\N		\N	\N	
983	Air Products	APD	USA200	Materials	281.01	\N		\N	\N	
984	Fortinet	FTNT	USA200	Technology	81.4	\N		\N	\N	
985	Simon Property Group	SPG	USA200	Real Estate	184.52	\N		\N	\N	
986	Sempra	SRE	USA200	Utilities	91.72	\N		\N	\N	
987	Occidental Petroleum	OXY	USA200	Energy	60.71	\N		\N	\N	
988	Baker Hughes	BKR	USA200	Energy	60.35	\N		\N	\N	
989	Digital Realty	DLR	USA200	Real Estate	173.3	\N		\N	\N	
990	Paccar	PCAR	USA200	Industrials	111.26	\N		\N	\N	
991	TE Connectivity	TEL	USA200	Technology	195.84	\N		\N	\N	
992	Realty Income	O	USA200	Real Estate	60.95	\N		\N	\N	
993	ONEOK	OKE	USA200	Energy	89.21	\N		\N	\N	
994	Arthur J. Gallagher & Co.	AJG	USA200	Financials	214.82	\N		\N	\N	
995	Aflac	AFL	USA200	Financials	106.22	\N		\N	\N	
996	Truist Financial	TFC	USA200	Financials	44.16	\N		\N	\N	
997	Ciena Corporation	CIEN	USA200	Technology	383.89	\N		\N	\N	
998	AutoZone	AZO	USA200	Consumer Discretionary	3282.9	\N		\N	\N	
999	Diamondback Energy	FANG	USA200	Energy	192.54	\N		\N	\N	
1000	Allstate	ALL	USA200	Financials	205.62	\N		\N	\N	
\.


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 1, false);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 1, true);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 28, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 7, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 20, true);


--
-- Name: portfolio_stock_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.portfolio_stock_id_seq', 1000, true);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: portfolio_stock portfolio_stock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portfolio_stock
    ADD CONSTRAINT portfolio_stock_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

