# Generated by Django 5.2.12 on 2026-03-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=50)),
                ('portfolio', models.CharField(choices=[('NIFTY200', 'NIFTY200'), ('USA200', 'USA200')], max_length=20)),
                ('sector', models.CharField(max_length=100)),
                ('ltp', models.FloatField(blank=True, null=True)),
                ('change_percent', models.FloatField(blank=True, null=True)),
                ('market_cap', models.CharField(blank=True, max_length=100, null=True)),
                ('high_52w', models.FloatField(blank=True, null=True)),
                ('low_52w', models.FloatField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
